#!/usr/bin/env bash
#
# Entry point for the systemd unit written by install.sh.
#
# A service starts without the user's shell profile, so the FDS environment is pulled in from
# service.env (generated by scripts/configure.py, meant to be edited by hand when needed)
# before FDSRouter itself is started from the virtual environment.

set -e

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if [ -f "$REPO_DIR/service.env" ]; then
    # FDS6VARS.sh and comparable vendor scripts read unset variables and may exit non-zero,
    # so neither errexit nor nounset may be active while sourcing them.
    set +e +u
    # shellcheck source=/dev/null
    . "$REPO_DIR/service.env"
    set -e
fi

cd "$REPO_DIR"
exec "$REPO_DIR/.venv/bin/fdsrouter" start --no-browser
